"""Probability

Revision ID: 0abf14c64137
Revises: 9e109331ec9b
Create Date: 2023-04-29 18:48:31.455276

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0abf14c64137'
down_revision = '9e109331ec9b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('probability',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('prob_win', sa.Float(precision=2), nullable=True),
    sa.Column('prob_gold', sa.Float(precision=2), nullable=True),
    sa.Column('prob_exp', sa.Float(precision=2), nullable=True),
    sa.Column('prob_towers', sa.JSON(), nullable=True),
    sa.Column('prob_drakes', sa.JSON(), nullable=True),
    sa.Column('prob_inhibitors', sa.JSON(), nullable=True),
    sa.Column('prob_elders', sa.JSON(), nullable=True),
    sa.Column('prob_barons', sa.JSON(), nullable=True),
    sa.Column('prob_heralds', sa.JSON(), nullable=True),
    sa.Column('prob_kills', sa.JSON(), nullable=True),
    sa.Column('prob_deaths', sa.JSON(), nullable=True),
    sa.Column('prob_assists', sa.JSON(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['league_id'], ['league.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('probability')
    # ### end Alembic commands ###
