"""Play

Revision ID: 8894145861a1
Revises: c892ac4c7551
Create Date: 2023-06-27 12:50:34.007807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8894145861a1'
down_revision = 'c892ac4c7551'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE bet CASCADE')
    op.execute('TRUNCATE TABLE match CASCADE')
    op.execute('TRUNCATE TABLE result CASCADE')
    op.create_table('play',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('local', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('bet', sa.Column('play_id', sa.Integer(), nullable=False))
    op.drop_constraint('bet_match_id_fkey', 'bet', type_='foreignkey')
    op.drop_constraint('bet_team_id_fkey', 'bet', type_='foreignkey')
    op.create_foreign_key(None, 'bet', 'play', ['play_id'], ['id'])
    op.drop_column('bet', 'match_id')
    op.drop_column('bet', 'team_id')
    op.drop_constraint('match_local_team_id_fkey', 'match', type_='foreignkey')
    op.drop_constraint('match_away_team_id_fkey', 'match', type_='foreignkey')
    op.drop_column('match', 'away_team_id')
    op.drop_column('match', 'local_team_id')
    op.add_column('result', sa.Column('play_id', sa.Integer(), nullable=False))
    op.drop_index('idx_match_set_team', table_name='result')
    op.drop_constraint('result_team_id_fkey', 'result', type_='foreignkey')
    op.drop_constraint('result_match_id_fkey', 'result', type_='foreignkey')
    op.create_foreign_key(None, 'result', 'play', ['play_id'], ['id'])
    op.drop_column('result', 'match_id')
    op.drop_column('result', 'team_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE bet CASCADE')
    op.execute('TRUNCATE TABLE match CASCADE')
    op.execute('TRUNCATE TABLE result CASCADE')
    op.add_column('result', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('result', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('result_play_id_fkey', 'result', type_='foreignkey')
    op.create_foreign_key('result_match_id_fkey', 'result', 'match', ['match_id'], ['id'])
    op.create_foreign_key('result_team_id_fkey', 'result', 'team', ['team_id'], ['id'])
    op.create_index('idx_match_set_team', 'result', ['match_id', 'set', 'team_id'], unique=False)
    op.drop_column('result', 'play_id')
    op.add_column('match', sa.Column('local_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match', sa.Column('away_team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('match_away_team_id_fkey', 'match', 'team', ['away_team_id'], ['id'])
    op.create_foreign_key('match_local_team_id_fkey', 'match', 'team', ['local_team_id'], ['id'])
    op.add_column('bet', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('bet', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('bet_play_id_fkey', 'bet', type_='foreignkey')
    op.create_foreign_key('bet_team_id_fkey', 'bet', 'team', ['team_id'], ['id'])
    op.create_foreign_key('bet_match_id_fkey', 'bet', 'match', ['match_id'], ['id'])
    op.drop_column('bet', 'play_id')
    op.drop_table('play')
    # ### end Alembic commands ###
