"""BettingOdd v2

Revision ID: 8d7ae259229c
Revises: fbc64064fe39
Create Date: 2023-06-09 17:13:02.359273

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '8d7ae259229c'
down_revision = 'fbc64064fe39'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('odd',
    sa.Column('type', sa.String(length=15), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('betting_odd_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['betting_odd_id'], ['betting_odd.id'], ),
    sa.PrimaryKeyConstraint('type', 'betting_odd_id')
    )
    op.drop_column('betting_odd', 'exp_odds')
    op.drop_column('betting_odd', 'barons_odds')
    op.drop_column('betting_odd', 'inhibitors_odds')
    op.drop_column('betting_odd', 'assists_odds')
    op.drop_column('betting_odd', 'gold_odds')
    op.drop_column('betting_odd', 'deaths_odds')
    op.drop_column('betting_odd', 'drakes_odds')
    op.drop_column('betting_odd', 'kills_odds')
    op.drop_column('betting_odd', 'heralds_odds')
    op.drop_column('betting_odd', 'win_odds')
    op.drop_column('betting_odd', 'elders_odds')
    op.drop_column('betting_odd', 'towers_odds')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('betting_odd', sa.Column('towers_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('elders_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('win_odds', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('heralds_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('kills_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('drakes_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('deaths_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('gold_odds', sa.REAL(), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('assists_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('inhibitors_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('barons_odds', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('exp_odds', sa.REAL(), autoincrement=False, nullable=False))
    op.drop_table('odd')
    # ### end Alembic commands ###
