"""User Update

Revision ID: 9f7d03e9490d
Revises: d9c93b0defcb
Create Date: 2023-05-18 15:51:24.188992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f7d03e9490d'
down_revision = 'd9c93b0defcb'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.String(), nullable=False))
    op.add_column('user', sa.Column('email', sa.String(), nullable=False))
    op.add_column('user', sa.Column('password', sa.String(), nullable=False))
    op.add_column('user', sa.Column('balance', sa.Integer(), nullable=True))
    op.add_column('user', sa.Column('img', sa.String(), nullable=True))
    op.create_unique_constraint(None, 'user', ['username'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('user_username_key', 'user', type_='unique')
    op.drop_column('user', 'balance')
    op.drop_column('user', 'password')
    op.drop_column('user', 'email')
    op.drop_column('user', 'username')
    op.drop_column('user', 'img')
    # ### end Alembic commands ###
