"""Match_v2

Revision ID: c892ac4c7551
Revises: 8d7ae259229c
Create Date: 2023-06-11 19:35:42.499174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c892ac4c7551'
down_revision = '8d7ae259229c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('final_set', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('result', sa.JSON(), nullable=True))
    op.drop_index('idx_match_set_team', table_name='result')
    op.create_index('idx_match_set_team', 'result', ['match_id', 'set', 'team_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_set_team', table_name='result')
    op.create_index('idx_match_set_team', 'result', ['match_id', 'set', 'team_id'], unique=False)
    op.drop_column('match', 'result')
    op.drop_column('match', 'final_set')
    # ### end Alembic commands ###
