"""Participation-Team

Revision ID: c9c4f56419a2
Revises: de72e1e40ee6
Create Date: 2023-04-24 17:24:38.483055

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9c4f56419a2'
down_revision = 'de72e1e40ee6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('acronym', sa.String(), nullable=False),
    sa.Column('img', sa.String(), nullable=True),
    sa.Column('website', sa.String(), nullable=True),
    sa.Column('nationality', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('participation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.Column('season_id', sa.Integer(), nullable=True),
    sa.Column('team_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['season_id'], ['season.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('participation')
    op.drop_table('team')
    # ### end Alembic commands ###
