"""Bet EarlyUser

Revision ID: d9c93b0defcb
Revises: 0abf14c64137
Create Date: 2023-05-12 21:38:26.384001

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9c93b0defcb'
down_revision = '0abf14c64137'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', sa.Enum('WINNER', 'EXP', 'GOLD', 'DRAKES', 'INHIBITORS', 'ELDER', 'TOWER', 'BARON', 'HERALD', 'KILL', 'DEATH', 'ASSIST', name='bettype'), nullable=False),
    sa.Column('subtype', sa.Integer(), nullable=True),
    sa.Column('multiplier', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('betting_odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('win_odds', sa.Float(precision=2), nullable=False),
    sa.Column('gold_odds', sa.Float(precision=2), nullable=False),
    sa.Column('exp_odds', sa.Float(precision=2), nullable=False),
    sa.Column('towers_odds', sa.JSON(), nullable=False),
    sa.Column('drakes_odds', sa.JSON(), nullable=False),
    sa.Column('inhibitors_odds', sa.JSON(), nullable=False),
    sa.Column('elders_odds', sa.JSON(), nullable=False),
    sa.Column('barons_odds', sa.JSON(), nullable=False),
    sa.Column('heralds_odds', sa.JSON(), nullable=False),
    sa.Column('kills_odds', sa.JSON(), nullable=False),
    sa.Column('deaths_odds', sa.JSON(), nullable=False),
    sa.Column('assists_odds', sa.JSON(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['match.id'], ),
    sa.ForeignKeyConstraint(['team_id'], ['team.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bet')
    op.drop_table('user')
    op.drop_table('betting_odds')
    op.execute('DROP TYPE bettype')
    # ### end Alembic commands ###
