"""Play v2

Revision ID: d9ebb0699271
Revises: 8894145861a1
Create Date: 2023-06-27 16:00:52.894395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd9ebb0699271'
down_revision = '8894145861a1'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE betting_odd CASCADE')
    op.add_column('betting_odd', sa.Column('updated', sa.Boolean(), server_default='0', nullable=False))
    op.add_column('betting_odd', sa.Column('play_id', sa.Integer(), nullable=False))
    op.drop_constraint('betting_odd_match_id_fkey', 'betting_odd', type_='foreignkey')
    op.drop_constraint('betting_odd_team_id_fkey', 'betting_odd', type_='foreignkey')
    op.create_foreign_key(None, 'betting_odd', 'play', ['play_id'], ['id'])
    op.drop_column('betting_odd', 'team_id')
    op.drop_column('betting_odd', 'match_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute('TRUNCATE TABLE betting_odd CASCADE')
    op.add_column('betting_odd', sa.Column('match_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('betting_odd', sa.Column('team_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint('betting_odd_play_id_fkey', 'betting_odd', type_='foreignkey')
    op.create_foreign_key('betting_odd_team_id_fkey', 'betting_odd', 'team', ['team_id'], ['id'])
    op.create_foreign_key('betting_odd_match_id_fkey', 'betting_odd', 'match', ['match_id'], ['id'])
    op.drop_column('betting_odd', 'play_id')
    op.drop_column('betting_odd', 'updated')
    # ### end Alembic commands ###
